import type { taskOrAward } from '@/types/taskOrAwards'

export const awards: taskOrAward[] = [
  {
    icon: 'Hamburger',
    title: 'Поход в фастфуд',
    price: -1500,
    id: 1,
    discount: 2 / 3,
    display: true,
  },
  {
    icon: 'Utensils',
    title: 'Поход в ресторан',
    price: -4000,
    id: 2,
    discount: 0.75,
    display: true,
  },
  {
    icon: 'PlugZap',
    title: 'Аналог дайсон',
    price: -200000,
    id: 3,
    discount: 0.7,
    display: true,
  },
  {
    icon: 'BriefcaseBusiness',
    title: 'Уволиться с работы',
    price: -1000000,
    id: 4,
    discount: 0.85,
    display: true,
  },
  {
    icon: 'BriefcaseBusiness',
    title: 'Массаж спины 20 мин',
    price: -2500,
    id: 5,
    discount: 0.5,
    display: true,
  },
  {
    icon: 'BriefcaseBusiness',
    title: 'Массаж ножек по 7 мин',
    price: -1500,
    id: 6,
    discount: 2 / 3,
    display: true,
  },
  {
    icon: 'BriefcaseBusiness',
    title: 'Старик хинкалыч',
    price: -2500,
    id: 7,
    discount: 4 / 5,
    display: true,
  },
  {
    icon: 'BriefcaseBusiness',
    title: 'Купить домашнее растение',
    price: -1500,
    id: 8,
    discount: 4 / 5,
    display: true,
  },
]
