import type { TaskOrAward } from '@/types/TaskOrAwards'

export const tasks: TaskOrAward[] = [
  {
    icon: 'bed-double',
    title: 'Лечь спать до 10 часов',
    price: 50,
    id: 1,
    discount: 2,
    display: false,
  },
  {
    icon: 'cooking-pot',
    title: 'Помыть посуду',
    price: 100,
    id: 2,
    discount: 1.5,
    display: true,
  },
  {
    icon: 'footprints',
    title: 'Прогулка 20 минут по парку',
    price: 100,
    id: 3,
    discount: 2.5,
    display: true,
  },
  {
    icon: 'smile',
    title: 'Чистка зубов 2 раза в день',
    price: 100,
    id: 4,
    discount: 1.2,
    display: true,
  },
  {
    icon: 'biceps-flexed',
    title: 'Зарядка для спины',
    price: 200,
    id: 5,
    discount: 1.2,
    display: true,
  },
  {
    icon: 'brush-cleaning',
    title: 'Уборка 15 минут',
    price: 100,
    id: 6,
    discount: 1.5,
    display: true,
  },
  {
    icon: 'bike',
    title: 'Велотренажёр 10 минут',
    price: 150,
    id: 7,
    discount: 2,
    display: true,
  },
  {
    icon: 'heart-handshake',
    title: 'Массаж ручек по 7 мин',
    price: 1000,
    id: 8,
    discount: 1.2,
    display: true,
  },
  {
    icon: 'instagram',
    title: 'Распечатать фотографии для книги приключений',
    price: 1000,
    id: 9,
    discount: 1.1,
    display: true,
  },
  {
    icon: 'book-heart',
    title: 'Выполнить задание из книги приключений',
    price: 1500,
    id: 10,
    discount: 1.25,
    display: true,
  },
  {
    icon: 'bed-double',
    title: 'Лечь спать до 11 часов',
    price: 50,
    id: 11,
    discount: 2,
    display: true,
  },
  {
    icon: 'volleyball',
    title: 'Доделать балаклавы',
    price: 1000,
    id: 12,
    discount: 1.2,
    display: true,
  },
  {
    icon: 'person-standing',
    title: 'Медитация 5 минут',
    price: 75,
    id: 13,
    discount: 4 / 3,
    display: true,
  },
  {
    icon: 'user',
    title: 'Массаж спины 15 мин',
    price: 1000,
    id: 14,
    discount: 5 / 4,
    display: true,
  },
]
