import type { taskOrAward } from '@/types/taskOrAwards'

export const tasks: taskOrAward[] = [
  {
    icon: 'BedDouble',
    title: 'Лечь спать до 10 часов',
    price: 50,
    id: 1,
    discount: 2,
    display: false,
  },
  {
    icon: 'CookingPot',
    title: 'Помыть посуду',
    price: 100,
    id: 2,
    discount: 1.5,
    display: true,
  },
  {
    icon: 'Footprints',
    title: 'Прогулка 20 минут по парку',
    price: 100,
    id: 3,
    discount: 2.5,
    display: true,
  },
  {
    icon: 'Smile',
    title: 'Чистка зубов 2 раза в день',
    price: 100,
    id: 4,
    discount: 1.2,
    display: true,
  },
  {
    icon: 'BicepsFlexed',
    title: 'Зарядка для спины',
    price: 200,
    id: 5,
    discount: 1.2,
    display: true,
  },
  {
    icon: 'BrushCleaning',
    title: 'Уборка 15 минут',
    price: 100,
    id: 6,
    discount: 1.5,
    display: true,
  },
  {
    icon: 'Bike',
    title: 'Велотренажёр 10 минут',
    price: 150,
    id: 7,
    discount: 2,
    display: true,
  },
  {
    icon: 'HeartHandshake',
    title: 'Массаж ручек по 10 мин',
    price: 250,
    id: 8,
    discount: 1.2,
    display: true,
  },
  {
    icon: 'HeartHandshake',
    title: 'Распечатать фотографии для книги приключений',
    price: 1000,
    id: 9,
    discount: 1.1,
    display: true,
  },
  {
    icon: 'HeartHandshake',
    title: 'Выполнить задание из книги приключений',
    price: 1500,
    id: 10,
    discount: 1.25,
    display: true,
  },
  {
    icon: 'BedDouble',
    title: 'Лечь спать до 11 часов',
    price: 50,
    id: 11,
    discount: 2,
    display: true,
  },
]
